// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmHome struct {
	*vcl.TForm
	StatusBar        *vcl.TStatusBar
	Pnl_info         *vcl.TPanel
	Lbl_name         *vcl.TLabel
	Lbl_port         *vcl.TLabel
	Lbl_version      *vcl.TLabel
	Tray_icon        *vcl.TTrayIcon
	P_menu           *vcl.TPopupMenu
	PM_open_web_page *vcl.TMenuItem
	PM_show          *vcl.TMenuItem
	PM_close         *vcl.TMenuItem

	// ::private::
	TFrmHomeFields
}

var FrmHome *TFrmHome

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmHome)

func NewFrmHome(owner vcl.IComponent) (root *TFrmHome) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmHome.gfm
var FrmHomeBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmHome, &FrmHomeBytes)
