// Automatically generated by the res2go, do not edit.

package about

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmAbout struct {
	*vcl.TForm
	Lbl_server_name    *vcl.TLabel
	Lbl_server_version *vcl.TLabel
	Img_logo           *vcl.TImage

	// ::private::
	TFrmAboutFields
}

var FrmAbout *TFrmAbout

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmAbout)

func NewFrmAbout(owner vcl.IComponent) (root *TFrmAbout) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmAbout.gfm
var FrmAboutBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmAbout, &FrmAboutBytes)
