// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmHome struct {
	*vcl.TForm
	StatusBar        *vcl.TStatusBar
	Pnl_main         *vcl.TPanel
	Pnl_header       *vcl.TPanel
	Pnl_info         *vcl.TPanel
	Lbl_name         *vcl.TLabel
	Lbl_port         *vcl.TLabel
	Pnl_actions      *vcl.TPanel
	Btn_server_run   *vcl.TSpeedButton
	Btn_clear_log    *vcl.TSpeedButton
	Pnl_body         *vcl.TPanel
	Mmo_run_log      *vcl.TMemo
	Main_menu        *vcl.TMainMenu
	Meu_item_help    *vcl.TMenuItem
	Meu_item_about   *vcl.TMenuItem
	Timer            *vcl.TTimer
	Tray_icon        *vcl.TTrayIcon
	P_menu           *vcl.TPopupMenu
	PM_show          *vcl.TMenuItem
	PM_close         *vcl.TMenuItem
	IList            *vcl.TImageList
	PM_open_web_page *vcl.TMenuItem

	// ::private::
	TFrmHomeFields
}

var FrmHome *TFrmHome

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmHome)

func NewFrmHome(owner vcl.IComponent) (root *TFrmHome) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmHome.gfm
var FrmHomeBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmHome, &FrmHomeBytes)
